### ISSUE TITLE
Loading CSS modules

### ISSUE THREAD

**Issue by musicbyjing** [pascalw/dashbling#36]
I'm receiving the following error when trying to import css modules: 
```
Module parse failed: Unexpected token
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.
```
In particular, this has happened for [Ant Design](https://ant.design/docs/react/introduce#Usage) as well as [this progress bar framework](https://github.com/kevinsqi/react-circular-progressbar#usage). I'm pretty sure Dashbling has `css-loader` and `style-loader` already in the webpack configuration so I'm not sure what's wrong.

**Comment by pascalw** [comment]
This is because node_modules are [excluded](https://github.com/pascalw/dashbling/blob/master/packages/build-support/webpack.config.js#L77) in the Webpack config, for performance reasons.

You should be able to make it work by [customizing the Webpack config](https://github.com/pascalw/dashbling/blob/master/docs/customize-build-process.md), for example like this:

```js
// dashbling.config.js
module.exports = {
  webpackConfig: config => {
    config.module.rules = config.module.rules.map(r => {
      if(r.test.toString() === /\.s?css$/.toString()) {
        delete(r.exclude);
      }

      return r;
    });

    return config;
  }
};
```

This removes the exclusion, so Webpack will process (s)css files in node_modules as well.

**Comment by pascalw** [comment]
@musicbyjing I haven't heard back from you so I'm closing the issue. If you have any other questions feel free to reopen!
